### ISSUE TITLE
Problem in grid save

### ISSUE THREAD

**Issue by peruginia** [vitmalina/w2ui#2272]
With the github dist js If i put a grid with editable field and i click save i receive

w2ui-2.x.js:12677 
        
       Uncaught TypeError: Cannot read properties of undefined (reading 'url')
    at w2grid.request (w2ui-2.x.js:12677:28)                           ------->  **here i have  edata.url**
    at w2grid.save (w2ui-2.x.js:12972:18)                                -------> **here i have  edata.detail.url**
    at w2toolbar.<anonymous> (w2ui-2.x.js:16016:26)
    at w2toolbar.trigger (w2ui-2.x.js:206:34)
    at w2toolbar.click (w2ui-2.x.js:6617:30)
    at HTMLDivElement.<anonymous> (w2ui-2.x.js:2930:49)

in the procedure request the field url is in event.url and not in event.detail.url  

solved in [src](https://github.com/vitmalina/w2ui/tree/master/src)/w2grid.js     line 2738

From 
edata = { url, postData: params, httpHeaders: this.httpHeaders }

to:
let detail = { url, postData: params, httpHeaders: this.httpHeaders }
edata = { detail,url, postData: params, httpHeaders: this.httpHeaders }

**Comment by AlexKovynev** [comment]
can you check more simple solution edata = { detail: { url, postData: params, httpHeaders: this.httpHeaders } }

is it work?

**Comment by peruginia** [comment]
I have just tested,
your solution  
edata = { detail: { url, postData: params, httpHeaders: this.httpHeaders } }

work well and is more simple :)

**Comment by AlexKovynev** [comment]
so i propose PR, will wait
