### ISSUE TITLE
Grid save method in onChnage event throw error.

### ISSUE THREAD

**Issue by artistmonkey** [vitmalina/w2ui#2418]
onChange: function (event) {
                    event.done(function () {
                        w2ui[event.target].save();
                    });                  
                },

when cell edit:
w2ui-2.0.min.js:318 Uncaught TypeError: Cannot read properties of null (reading 'tr')
    at w2grid.editDone (w2ui-2.0.min.js:318:4261)
    at w2ui-2.0.min.js:318:1989
editDone @ w2ui-2.0.min.js:318
(anonymous) @ w2ui-2.0.min.js:318
setTimeout (async)
(anonymous) @ w2ui-2.0.min.js:318

**Comment by artistmonkey** [comment]
finishing the edit with 'Enter' key produced the above error. But if I click other cells to finish editing, it won't throw an error.

**Comment by vitmalina** [comment]
I cannot repeat this problem here: https://w2ui.com/web/demos/#/grid/21. Can you please create JS fiddle where the problem is repeated?

**Comment by artistmonkey** [comment]
I've added in grid onChange event
https://jsfiddle.net/1h759uo8/1/

**Comment by artistmonkey** [comment]
Making delay to save can overcome error
onChange: function (event) {
                    var grid = this;
                    event.done(function () {
                        setTimeout(function() {
                            grid.save();
                        }, 200);
                    });                  
                },
