### ISSUE TITLE
Grid delete with force not passing "options" argument to "message" method

### ISSUE THREAD

**Issue by zbeebembg** [vitmalina/w2ui#2599]
**What is current behavior**
Just recently I noticed an error being thrown when I try to delete records from a grid. After the delete confirmation, w2ui calls the grid delete method with "force" = true. This then calls the grid "message" method with no arguments (grid.message()). The message method then calls the utils message method, which takes two arguments "where" and "options". The call is failing within the utils message method, where it is checking logic for options.text and options.body. Below is the console traceback:

Uncaught TypeError: Cannot read properties of undefined (reading 'text')
    at Utils.message (w2ui.js:2039:22)
    at w2grid.message (w2ui.js:20144:24)
    at w2grid.delete (w2ui.js:15154:25)
    at w2ui.js:15174:32
    at w2base.<anonymous> (w2ui.js:2117:50)
    at w2base.trigger (w2ui.js:209:34)
    at options.action (w2ui.js:2235:33)
    at HTMLButtonElement.<anonymous> (w2ui.js:3245:49)

**What is desired behavior**
Maybe pass an empty or default options object when calling the grid message method?

**Link to jsfidle/codepan with sample code**
[W2UI Grid Delete Error - JS Fiddle](https://jsfiddle.net/zacharybeebe/r0h6xdyw/4/)

**Comment by zbeebembg** [comment]
This has been fixed as of 01/03/2025, closing
